# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    event_images_directory: '%kernel.project_dir%/public/uploads/events'
    upload_directory: '%kernel.project_dir%/public/uploads/'
    ml_endpoint: '%env(ML_ENDPOINT)%'
    app_name: 'Knowlity'
    wkhtmltopdf_binary_path: 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    wkhtmltoimage_binary_path: 'C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe'

services:
    
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    knp.snappy.pdf:
        class: Knp\Snappy\Pdf
        arguments:
            - '%wkhtmltopdf_binary_path%'
    
    knp.snappy.image:
        class: Knp\Snappy\Image
        arguments:
            - '%wkhtmltoimage_binary_path%'

    App\Service\PdfGenerator:
        arguments:
            $twig: '@twig'
            $parameterBag: '@parameter_bag'
            $logger: '@logger' # Optional
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\MailService:
        arguments:
            $mailer: '@mailer.mailer'


    Knp\Component\Pager\PaginatorInterface:
        alias: knp_paginator        
    App\Service\ProfanityCheckerService: ~
    App\Service\PdfService: ~
